'use strict';
var Alexa = require('alexa-sdk');

var APP_ID = 'amzn1.ask.skill.ef5df7a4-dcca-4f10-8e6f-3b8d5c516146';
var SKILL_NAME = 'Climate Change Facts';

/**
 * Array containing climate change facts.
 */
var CLIMATE_CHANGE_FACTS = [
    "Global sea level rose about 8 inches in the last century. The rate in the last two decades, however, is nearly double that of the last century.",
    "All three major global surface temperature reconstructions show that Earth has warmed since 1880. Most of the warming occurred in the past 35 years, with 15 of the 16 warmest years on record occurring since 2001.",
    "The year 2015 was the first time the global average temperatures were 1 degree Celsius or more above the 1880-1899 average. The oceans have absorbed much of this increased heat, with the top 700 meters (about 2,300 feet) of ocean showing warming of 0.302 degrees Fahrenheit since 1969.",
    "The Greenland and Antarctic ice sheets have decreased in mass. Data from NASA's Gravity Recovery and Climate Experiment show Greenland lost 150 to 250 cubic kilometers (36 to 60 cubic miles) of ice per year between 2002 and 2006, while Antarctica lost about 152 cubic kilometers (36 cubic miles) of ice between 2002 and 2005.",
    "Both the extent and thickness of Arctic sea ice has declined rapidly over the last several decades.",
    "Glaciers are retreating almost everywhere around the world — including in the Alps, Himalayas, Andes, Rockies, Alaska and Africa.",
    "The number of record high temperature events in the United States has been increasing, while the number of record low temperature events has been decreasing, since 1950. The U.S. has also witnessed increasing numbers of intense rainfall events.",
    "Since the beginning of the Industrial Revolution, the acidity of surface ocean waters has increased by about 30 percent. This increase is the result of humans emitting more carbon dioxide into the atmosphere and hence more being absorbed into the oceans. The amount of carbon dioxide absorbed by the upper layer of the oceans is increasing by about 2 billion tons per year.",
    "The temperature inside the Sun can reach 15 million degrees Celsius.",
    "Satellite observations reveal that the amount of spring snow cover in the Northern Hemisphere has decreased over the past five decades and that the snow is melting earlier.",
    "Since 1978, a series of satellite instruments have measured the energy output of the sun directly. The satellite data show a very slight drop in solar irradiance (which is a measure of the amount of energy the sun gives off) over this time period. So the sun doesn't appear to be responsible for the warming trend observed over the past several decades. Longer-term estimates of solar irradiance have been made using sunspot records and other so-called proxy indicators, such as the amount of carbon in tree rings. The most recent analyses of these proxies indicate that solar irradiance changes cannot plausibly account for more than 10 percent of the 20th century’s warming.",
    "On Earth, human activities are changing the natural greenhouse. Over the last century the burning of fossil fuels like coal and oil has increased the concentration of atmospheric carbon dioxide (CO2). This happens because the coal or oil burning process combines carbon with oxygen in the air to make CO2. To a lesser extent, the clearing of land for agriculture, industry, and other human activities has increased concentrations of greenhouse gases.",
    "The consequences of changing the natural atmospheric greenhouse are difficult to predict, but certain effects seem likely. First: On average, Earth will become warmer. Some regions may welcome warmer temperatures, but others may not. Second: Warmer conditions will probably lead to more evaporation and precipitation overall, but individual regions will vary, some becoming wetter and others dryer. Third: A stronger greenhouse effect will warm the oceans and partially melt glaciers and other ice, increasing sea level. Ocean water also will expand if it warms, contributing further to sea level rise. Fourth: Meanwhile, some crops and other plants may respond favorably to increased atmospheric CO2, growing more vigorously and using water more efficiently. At the same time, higher temperatures and shifting climate patterns may change the areas where crops grow best and affect the makeup of natural plant communities.",
    "Most climate scientists agree the main cause of the current global warming trend is human expansion of the greenhouse effect — warming that results when the atmosphere traps heat radiating from Earth toward space.",
    "Certain gases in the atmosphere block heat from escaping. Long-lived gases that remain semi-permanently in the atmosphere and do not respond physically or chemically to changes in temperature are described as forcing climate change. Gases, such as water vapor, which respond physically or chemically to changes in temperature are seen as feedbacks.",
    "Gases that contribute to the greenhouse effect include water vapor, carbon dioxide, methane, nitrous oxide, and chlorofluorocarbons.",
    "Water vapor is the most abundant greenhouse gas, but importantly, it acts as a feedback to the climate. Water vapor increases as the Earth's atmosphere warms, but so does the possibility of clouds and precipitation, making these some of the most important feedback mechanisms to the greenhouse effect.",
    "Carbon dioxide (CO2) is a minor but very important component of the atmosphere. Carbon dioxide is released through natural processes such as respiration and volcano eruptions and through human activities such as deforestation, land use changes, and burning fossil fuels. Humans have increased atmospheric CO2 concentration by more than a third since the Industrial Revolution began. This is the most important long-lived forcing of climate change.",
    "Methane is hydrocarbon gas produced both through natural sources and human activities, including the decomposition of wastes in landfills, agriculture, and especially rice cultivation, as well as ruminant digestion and manure management associated with domestic livestock. On a molecule-for-molecule basis, methane is a far more active greenhouse gas than carbon dioxide, but also one which is much less abundant in the atmosphere.",
    "Nitrous oxide is a powerful greenhouse gas produced by soil cultivation practices, especially the use of commercial and organic fertilizers, fossil fuel combustion, nitric acid production, and biomass burning.",
    "Chlorofluorocarbons (CFCs) are synthetic compounds entirely of industrial origin used in a number of applications, but now largely regulated in production and release to the atmosphere by international agreement for their ability to contribute to destruction of the ozone layer. They are also greenhouse gases.",
    "In its Fifth Assessment Report, the Intergovernmental Panel on Climate Change, a group of 1,300 independent scientific experts from countries all over the world under the auspices of the United Nations, concluded there's a more than 95 percent probability that human activities over the past 50 years have warmed our planet.",
    "The industrial activities that our modern civilization depends upon have raised atmospheric carbon dioxide levels from 280 parts per million to 400 parts per million in the last 150 years. The Intergovernmental Panel on Climate Change concludes there's a better than 95 percent probability that human-produced greenhouse gases such as carbon dioxide, methane and nitrous oxide have caused much of the observed increase in Earth's temperatures over the past 50 years.",
    "It's reasonable to assume that changes in the sun's energy output would cause the climate to change. Studies show that solar variability has played a role in past climate changes. But several lines of evidence show that current global warming cannot be explained by changes in energy from the sun. First: Since 1750, the average amount of energy coming from the sun either remained constant or increased slightly. Second: If the warming were caused by a more active sun, then scientists would expect to see warmer temperatures in all layers of the atmosphere. Instead, they have observed a cooling in the upper atmosphere, and a warming at the surface and in the lower parts of the atmosphere. That's because greenhouse gases are trapping heat in the lower atmosphere. Third: Climate models that include solar irradiance changes can’t reproduce the observed temperature trend over the past century or more without including a rise in greenhouse gases.",
    "Global climate change has already had observable effects on the environment. Glaciers have shrunk, ice on rivers and lakes is breaking up earlier, plant and animal ranges have shifted and trees are flowering sooner.",
    "Effects that scientists had predicted in the past would result from global climate change are now occurring: loss of sea ice, accelerated sea level rise and longer, more intense heat waves.",
    "Scientists have high confidence that global temperatures will continue to rise for decades to come, largely due to greenhouse gases produced by human activities. The Intergovernmental Panel on Climate Change (IPCC), which includes more than 1,300 scientists from the United States and other countries, forecasts a temperature rise of 2.5 to 10 degrees Fahrenheit over the next century.",
    "The IPCC predicts that increases in global mean temperature of less than 1.8 to 5.4 degrees Fahrenheit (1 to 3 degrees Celsius) above 1990 levels will produce beneficial impacts in some regions and harmful ones in others. Net annual costs will increase over time as global temperatures increase.",
    "Global climate is projected to continue to change over this century and beyond. The magnitude of climate change beyond the next few decades depends primarily on the amount of heat-trapping gases emitted globally, and how sensitive the Earth’s climate is to those emissions.",
    "Because human-induced warming is superimposed on a naturally varying climate, the temperature rise has not been, and will not be, uniform or smooth across the United States or over time.",
    "In a future in which heat-trapping gas emissions continue to grow, increases of a month or more in the lengths of the frost-free and growing seasons are projected across most of the U.S. by the end of the century, with slightly smaller increases in the northern Great Plains. The largest increases in the frost-free season (more than eight weeks) are projected for the western U.S., particularly in high elevation and coastal areas. The increases will be considerably smaller if heat-trapping gas emissions are reduced.",
    "Average U.S. precipitation has increased since 1900, but some areas have had increases greater than the national average, and some areas have had decreases. More winter and spring precipitation is projected for the northern United States, and less for the Southwest, over this century.",
    "Projections of future climate over the U.S. suggest that the recent trend towards increased heavy precipitation events will continue. This trend is projected to occur even in regions where total precipitation is expected to decrease, such as the Southwest.",
    "Droughts in the Southwest and heat waves (periods of abnormally hot weather lasting days to weeks) everywhere are projected to become more intense, and cold waves less intense everywhere.",
    "Summer temperatures are projected to continue rising, and a reduction of soil moisture, which exacerbates heat waves, is projected for much of the western and central U.S. in summer. By the end of this century, what have been once-in-20-year extreme heat days (one-day events) are projected to occur every two or three years over most of the nation.",
    "The intensity, frequency and duration of North Atlantic hurricanes, as well as the frequency of the strongest (Category 4 and 5) hurricanes, have all increased since the early 1980s. The relative contributions of human and natural causes to these increases are still uncertain. Hurricane-associated storm intensity and rainfall rates are projected to increase as the climate continues to warm.",
    "Global sea level has risen by about 8 inches since reliable record keeping began in 1880. It is projected to rise another 1 to 4 feet by 2100. This is the result of added water from melting land ice and the expansion of seawater as it warms.",
    "In the next several decades, storm surges and high tides could combine with sea level rise and land subsidence to further increase flooding in many of these regions. Sea level rise will not stop in 2100 because the oceans take a very long time to respond to warmer conditions at the Earth’s surface. Ocean waters will therefore continue to warm and sea level will continue to rise for many centuries at rates equal to or higher than that of the current century.",
    "The Arctic Ocean is expected to become essentially ice free in summer before mid-century.",
    "Heat waves, heavy downpours and sea level rise pose growing challenges to many aspects of life in the Northeast. Infrastructure, agriculture, fisheries and ecosystems will be increasingly compromised. Many states and cities are beginning to incorporate climate change into their planning.",
    "In the Northwest United States, changes in the timing of streamflow are reducing water supplies for competing demands. Sea level rise, erosion, inundation, risks to infrastructure and increasing ocean acidity pose major threats. Increasing wildfire, insect outbreaks and tree diseases are causing widespread tree die-off.",
    "In the Southeast United States, sea level rise poses widespread and continuing threats to the region’s economy and environment. Extreme heat will affect health, energy, agriculture and more. Decreased water availability will have economic and environmental impacts.",
    "In the Midwest United States, extreme heat, heavy downpours and flooding will affect infrastructure, health, agriculture, forestry, transportation, air and water quality, and more. Climate change will also exacerbate a range of risks to the Great Lakes.",
    "In the Southwest United States, increased heat, drought and insect outbreaks, all linked to climate change, have increased wildfires. Declining water supplies, reduced agricultural yields, health impacts in cities due to heat, and flooding and erosion in coastal areas are additional concerns.",
    "Multiple studies published in peer-reviewed scientific journals1 show that 97 percent or more of actively publishing climate scientists agree: Climate-warming trends over the past century are extremely likely due to human activities. In addition, most of the leading scientific organizations worldwide have issued public statements endorsing this position.",
    "Global warming refers to the long-term warming of the planet. Global temperature shows a well-documented rise since the early 20th century and most notably since the late 1970s. Worldwide, since 1880 the average surface temperature has gone up by about 0.8°C (1.4 °F), relative to the mid-20th-century baseline (of 1951-1980).",
    "Climate change encompasses global warming, but refers to the broader range of changes that are happening to our planet. These include rising sea levels, shrinking mountain glaciers, accelerating ice melt in Greenland, Antarctica and the Arctic, and shifts in flower/plant blooming times. These are all consequences of the warming, which is caused mainly by people burning fossil fuels and putting out heat-trapping gases into the air. The terms global warming and climate change are sometimes used interchangeably, but strictly they refer to slightly different things.",
    "Weather refers to the more local changes in the climate we see around us, on short timescales from minutes to hours to days to weeks. Examples are familiar – rain, snow, clouds, winds, thunderstorms, heat waves and floods. Climate refers to longer-term averages (they may be regional or global), and can be thought of as the weather averaged over several seasons, years or decades. Climate change is harder for us to get a sense of because the timescales involved are much longer, and the impact of climate changes can be less immediate. Examples of climate change include several drier-than-normal summers, a trend of, say, winters becoming milder from our grandparents’ childhood to our own, or variations in effects like El Niño or La Niña.",
    "Humans have caused major climate changes to happen already, and we have set in motion more changes still. Even if we stopped emitting greenhouse gases today, global warming would continue to happen for at least several more decades if not centuries. That’s because it takes a while for the planet (for example, the oceans) to respond, and because carbon dioxide – the predominant heat-trapping gas – lingers in the atmosphere for hundreds of years. There is a time lag between what we do and when we feel it.",
    "In the absence of major action to reduce emissions, global temperature is on track to rise by an average of 6 °C (10.8 °F), according to the latest estimates. Some scientists argue a global disaster is already unfolding at the poles of the planet; the Arctic, for example, may be ice-free in the summer within just a few years. Yet other experts are concerned about Earth passing one or more tipping points – abrupt, perhaps irreversible changes that tip our climate into a new state.",
    "The vast majority of actively publishing climate scientists – 97 percent – agree that humans are causing global warming and climate change. Most of the leading science organizations around the world have issued public statements expressing this, including international and U.S. science academies, the United Nations Intergovernmental Panel on Climate Change and a whole host of reputable scientific bodies around the world). The number of peer-reviewed scientific papers that reject the consensus on human-caused global warming is a vanishingly small proportion of the published research. The small amount of dissent tends to come from a few vocal scientists who are not experts in the climate field or do not understand the scientific basis of long-term climate processes.",
    "The greenhouse effect is the way in which heat is trapped close to the surface of the Earth by greenhouse gases. These heat-trapping gases can be thought of as a blanket wrapped around the Earth, which keeps it toastier than it would be without them. Greenhouse gases include carbon dioxide, methane and nitrous oxides.",
    "Greenhouse gases arise naturally, and are part of the make-up of our atmosphere. Earth is sometimes called the Goldilocks planet – it’s not too hot, not too cold, and the conditions are just right to allow life, including us, to flourish. Part of what makes Earth so amenable is the naturally-arising greenhouse effect, which keeps the planet at a friendly 15 °C (59 °F) on average. But in the last century or so, humans have been interfering with the energy balance of the planet, mainly through the burning of fossil fuels that give off additional carbon dioxide into the air. The level of carbon dioxide in Earth’s atmosphere has been rising consistently for decades and traps extra heat near the surface of the Earth, causing temperatures to rise."
];

exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.APP_ID = APP_ID;
    alexa.registerHandlers(handlers);
    alexa.execute();
};

var handlers = {
    'LaunchRequest': function () {
        this.emit('GetFact');
    },
    'GetNewFactIntent': function () {
        this.emit('GetFact');
    },
    'GetFact': function () {
        // Get a random climate change fact from the climate change facts list
        var factIndex = Math.floor(Math.random() * CLIMATE_CHANGE_FACTS.length);
        var randomFact = CLIMATE_CHANGE_FACTS[factIndex];

        // Create speech output
        var speechOutput = "Here's your fact: " + randomFact;

        this.emit(':tellWithCard', speechOutput, SKILL_NAME, randomFact)
    },
    'AMAZON.HelpIntent': function () {
        var speechOutput = "These facts are sourced from NASA. To hear a fact, you can say tell me a climate change fact, or, you can say exit... What can I help you with?";
        var reprompt = "What can I help you with?";
        this.emit(':ask', speechOutput, reprompt);
    },
    'AMAZON.CancelIntent': function () {
        this.emit(':tell', 'Goodbye!');
    },
    'AMAZON.StopIntent': function () {
        this.emit(':tell', 'Goodbye!');
    }
};
